### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by Mechazo11** [MateuszOlko/DPOD#1]
Hi @MateuszOlko 
Are you still maintaining this repo? Can it be used to train DPOD for a custom dataset?

**Comment by MateuszOlko** [comment]
Hi,

as you can see the last commit is from 4 years ago. If I recall correctly the repo was left in a good state, so if you will be able to install all dependencies this should work. However, I will not be able to assist you in case of any troubles and can not guarantee the code's quality.

Just remember that the high quality of renders is essential in this approach. The simple rendering method provided in the repo was generally not sufficient to reproduce the original results.

I wish you all the best if you decide to work on this code.
Let me know how it went.

**Comment by Mechazo11** [comment]
Hi @MateuszOlko thank you very much for getting back to me. I appreciate the fact that you confirmed if I can get the dependencies figured out, the system will work.

I haven't decided yet but DPOD seems to be the most favorable 6D Pose Detector given a LineMOD compliant dataset, will train and infer object poses.  

I will try to keep you appraised and if not, at least I will link my public fork of DPOD in this thread.

Have a wonderful day.
With best regards,
@Mechazo11
